version: '3'
services:
  postgres:
    image: postgres:15.0-alpine
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: products-scraping
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - postgres
    ports:
      - "5432:5432"

  api:
    build:
      context: .
    volumes:
      - ./src:/app
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - postgres
  cron:
    build:
      context: .
    restart: unless-stopped
    env_file:
    - .env
    depends_on:
    - postgres
    networks:
      - postgres
    command: crond -f  # as a long-running foreground process

networks:
  postgres: