# Generated by Django 4.2.1 on 2023-06-19 17:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["imported_t"]},
        ),
    ]
